name: CPN CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: run tests
    timeout-minutes: 10

    strategy:
      matrix:
        go-version: [1.16, 1.17, 1.18]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            gofmt -s -l .
            echo "Please format the source code by running: make fmt"
            exit 1
          fi
      - name: Run tests
        run: make test
